python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_0.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_0_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_1.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_1_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_2.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_2_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_3.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_3_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_4.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_4_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_5.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_5_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_6.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_6_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_7.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_7_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_8.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_8_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_9.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_9_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_10.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_10_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_11.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_11_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_12.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_12_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_13.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_13_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_14.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_14_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_15.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_15_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_16.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_16_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_17.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_17_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_18.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_18_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_19.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_19_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_20.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_20_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_21.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_21_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_22.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_22_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_23.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_23_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_24.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_24_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_25.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_25_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_26.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_26_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_27.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_27_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_28.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_28_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_29.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_29_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_30.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_30_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_31.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_31_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_32.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_32_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_33.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_33_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_34.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_34_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_35.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_35_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_36.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_36_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_37.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_37_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_38.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_38_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_39.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_39_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_40.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_40_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_41.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_41_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_42.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_42_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_43.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_43_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_44.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_44_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_45.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_45_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_46.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_46_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_47.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_47_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_48.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_48_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_49.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_49_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_50.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_50_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_51.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_51_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_52.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_52_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_53.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_53_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_54.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_54_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_55.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_55_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_56.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_56_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_57.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_57_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_58.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_58_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_59.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_59_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_60.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_60_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_61.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_61_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_62.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_62_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_63.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_63_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_64.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_64_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_65.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_65_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_66.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_66_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_67.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_67_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_68.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_68_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_69.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_69_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_70.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_70_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_71.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_71_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_72.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_72_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_73.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_73_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_74.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_74_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_75.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_75_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_76.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_76_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_77.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_77_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_78.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_78_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_79.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_79_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_80.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_80_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_81.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_81_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_82.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_82_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_83.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_83_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_84.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_84_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_85.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_85_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_86.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_86_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_87.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_87_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_88.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_88_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_89.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_89_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_90.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_90_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_91.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_91_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_92.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_92_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_93.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_93_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_94.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_94_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_95.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_95_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_96.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_96_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_97.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_97_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_98.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_98_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_99.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_99_ --nmuons 10000 --njobs 5  \n
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_0.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_0_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_1.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_1_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_2.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_2_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_3.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_3_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_4.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_4_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_5.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_5_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_6.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_6_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_7.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_7_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_8.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_8_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_9.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_9_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_10.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_10_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_11.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_11_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_12.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_12_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_13.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_13_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_14.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_14_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_15.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_15_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_16.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_16_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_17.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_17_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_18.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_18_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_19.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_19_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_20.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_20_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_21.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_21_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_22.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_22_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_23.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_23_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_24.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_24_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_25.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_25_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_26.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_26_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_27.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_27_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_28.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_28_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_29.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_29_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_30.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_30_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_31.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_31_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_32.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_32_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_33.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_33_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_34.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_34_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_35.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_35_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_36.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_36_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_37.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_37_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_38.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_38_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_39.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_39_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_40.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_40_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_41.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_41_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_42.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_42_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_43.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_43_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_44.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_44_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_45.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_45_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_46.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_46_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_47.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_47_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_48.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_48_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_49.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_49_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_50.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_50_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_51.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_51_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_52.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_52_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_53.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_53_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_54.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_54_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_55.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_55_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_56.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_56_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_57.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_57_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_58.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_58_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_59.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_59_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_60.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_60_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_61.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_61_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_62.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_62_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_63.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_63_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_64.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_64_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_65.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_65_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_66.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_66_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_67.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_67_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_68.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_68_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_69.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_69_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_70.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_70_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_71.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_71_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_72.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_72_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_73.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_73_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_74.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_74_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_75.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_75_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_76.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_76_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_77.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_77_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_78.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_78_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_79.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_79_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_80.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_80_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_81.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_81_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_82.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_82_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_83.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_83_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_84.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_84_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_85.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_85_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_86.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_86_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_87.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_87_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_88.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_88_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_89.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_89_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_90.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_90_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_91.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_91_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_92.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_92_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_93.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_93_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_94.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_94_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_95.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_95_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_96.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_96_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_97.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_97_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_98.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_98_ --nmuons 10000 --njobs 5 
python submit_gm2.py --infile runBeamGunRing_CollimatorStudy_99.fcl --inpath /home/labounty/sim/circle_fcls --outpath /data/g2/users/labounty/gm2ringsim  --tarfile gm2_run1_v9_21_06.tar.gz --tarpath /home/labounty/ -t simutree_muonsAndPositrons_col8_99_ --nmuons 10000 --njobs 5 
